- name: Setup and run Bitcoin Tracker
  hosts: localhost
  become: yes
  tasks:

    - name: Clone repo if not present
      block:
        - name: Check if repo directory exists
          stat:
            path: "{{ playbook_dir }}/Junior-Dev-Exam"
          register: repo_dir

        - name: Clone the repo
          git:
            repo: https://github.com/AdamLevs/Junior-Dev-Exam.git
            dest: "{{ playbook_dir }}/Junior-Dev-Exam"
          when: not repo_dir.stat.exists

    - name: Remove conflicting containerd package
      apt:
        name: containerd
        state: absent
        purge: yes
      ignore_errors: yes

    - name: Install required dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker APT repository
      apt_repository:
        repo: >
          deb [arch={{ ansible_architecture | regex_replace('aarch64', 'arm64') | regex_replace('x86_64', 'amd64') }}
          signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        filename: docker
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker engine and plugins
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Build Docker images
      command: docker compose build
      args:
        chdir: "{{ playbook_dir }}/Junior-Dev-Exam"

    - name: Start only the DB container
      command: docker compose up -d db
      args:
        chdir: "{{ playbook_dir }}/Junior-Dev-Exam"

    - name: Wait for database to be ready
      pause:
        seconds: 10

    - name: Start the tracker container
      command: docker compose up  -d tracker
      args:
        chdir: "{{ playbook_dir }}/Junior-Dev-Exam"

    - name: Run the tracker container
      command: docker logs -f btc-tracker
      args:
        chdir: "{{ playbook_dir }}/Junior-Dev-Exam"